/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FacebookLogin {
    'text': string;
    'type': string;
    'width': string;
  }
  interface GithubLogin {
    'text': string;
    'type': string;
    'width': string;
  }
  interface GoogleLogin {
    'text': string;
    'type': string;
    'width': string;
  }
}

declare global {


  interface HTMLFacebookLoginElement extends Components.FacebookLogin, HTMLStencilElement {}
  var HTMLFacebookLoginElement: {
    prototype: HTMLFacebookLoginElement;
    new (): HTMLFacebookLoginElement;
  };

  interface HTMLGithubLoginElement extends Components.GithubLogin, HTMLStencilElement {}
  var HTMLGithubLoginElement: {
    prototype: HTMLGithubLoginElement;
    new (): HTMLGithubLoginElement;
  };

  interface HTMLGoogleLoginElement extends Components.GoogleLogin, HTMLStencilElement {}
  var HTMLGoogleLoginElement: {
    prototype: HTMLGoogleLoginElement;
    new (): HTMLGoogleLoginElement;
  };
  interface HTMLElementTagNameMap {
    'facebook-login': HTMLFacebookLoginElement;
    'github-login': HTMLGithubLoginElement;
    'google-login': HTMLGoogleLoginElement;
  }
}

declare namespace LocalJSX {
  interface FacebookLogin {
    'text'?: string;
    'type'?: string;
    'width'?: string;
  }
  interface GithubLogin {
    'text'?: string;
    'type'?: string;
    'width'?: string;
  }
  interface GoogleLogin {
    'text'?: string;
    'type'?: string;
    'width'?: string;
  }

  interface IntrinsicElements {
    'facebook-login': FacebookLogin;
    'github-login': GithubLogin;
    'google-login': GoogleLogin;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'facebook-login': LocalJSX.FacebookLogin & JSXBase.HTMLAttributes<HTMLFacebookLoginElement>;
      'github-login': LocalJSX.GithubLogin & JSXBase.HTMLAttributes<HTMLGithubLoginElement>;
      'google-login': LocalJSX.GoogleLogin & JSXBase.HTMLAttributes<HTMLGoogleLoginElement>;
    }
  }
}


